name: build123d
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - cadquery
  - pip
  - pip:
    - svgwrite 
    - anytree 
    - scipy 
    - ipython 
    - ocp_tessellate 
    - webcolors==1.12 
    - numpy 
    - numpy-quaternion 
    - cachetools==5.2.0 
    - ocp_vscode 
    - requests 
    - orjson 
    - urllib3 
    - certifi 
    - numpy-stl 
    - git+https://github.com/jdegenstein/py-lib3mf 
    - svgpathtools>=1.5.1,<2
    - svgelements>=1.9.1,<2
    - git+https://github.com/gumyr/build123d 
    - git+https://github.com/snoyer/ocpsvg
